### ISSUE TITLE
Python 3.8 wheels

### ISSUE THREAD

**Issue by clbarnes** [pattonw/rust-pyn5#133]

**Comment by clbarnes** [comment]
PR is merged, just need a new release.

**Comment by pattonw** [comment]
I'll look into it soon. I think there was something going wrong with the auto deployment to pypi through travis, but I forget how far I got in solving

**Comment by pattonw** [comment]
python 3.8 wheels are on pypi now. I haven't tried it out but it should work fine

**Comment by clbarnes** [comment]
Awesome, thank you!
