### ISSUE TITLE
Possible travis modifications

### ISSUE THREAD

**Issue by clbarnes** [pattonw/rust-pyn5#22]
- Use `after_success` or `deploy` with script
  - Do not deploy if tests fail on any job
- Factor repeated variables out of the `matrix.include` block if possible

[Some discussion here](https://github.com/pattonw/rust-pyn5/pull/20#discussion_r264511110)

**Comment by pattonw** [comment]
I'm pretty sure after_success and deploy run for each job

It looks like stages might be the best thing to use here. Each stage can have multiple jobs run in parrallel, but stages run sequentially dependent on the previous stage passing. https://docs.travis-ci.com/user/build-stages/

Normal repeated variables don't seem to work for stages other than the default test stage so each job in the deploy stage needs all of its values explicitly initialized. There does seem to be a hacky solution using yaml aliases though if we have a lot of deploy jobs

**Comment by clbarnes** [comment]
Good find! The travis docs aren't very clear on this point.
