### ISSUE TITLE
setuptools_rust vs pyo3-pack

### ISSUE THREAD

**Issue by pattonw** [pattonw/rust-pyn5#24]
### Move to pyo3-pack

pyo3-pack is the successor to setuptools_rust. Mixed layouts are not yet supported, but hopefully soon.
https://github.com/PyO3/pyo3-pack/issues/88

**Comment by clbarnes** [comment]
Looks like it's in: https://github.com/PyO3/pyo3-pack/pull/149

**Comment by clbarnes** [comment]
Released
