### ISSUE TITLE
h5py like interface

### ISSUE THREAD

**Issue by pattonw** [pattonw/rust-pyn5#5]
Wrap pyn5 with the interface defined in https://github.com/clbarnes/h5py_like/tree/master/h5py_like

**Comment by pattonw** [comment]
This would be nice to have the option of replacing z5py to avoid conda in https://github.com/funkey/gunpowder/blob/master/gunpowder/nodes/n5_source.py

**Comment by clbarnes** [comment]
See branch at https://github.com/clbarnes/rust-pyn5/tree/h5pylike , which uses https://github.com/clbarnes/h5py_like

**Comment by clbarnes** [comment]
Released!
